import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

enum NotificationType {
  newApplication,      // New student applied
  applicationUpdate,   // Application status changed
  studentMessage,      // Message from student
  studentDocument,     // Document uploaded by student
  systemAlert,         // System maintenance, updates
  payment,             // Payment received or failed
  reminder,            // Reminder for deadlines
  report,              // Reports generated
  announcement,        // Admin announcements
  internshipClosed,    // IT position closed
  internshipCreated,   // New IT created
  lowSlots,            // Low on available slots
  verification,        // Student/document verification
}

class CompanyNotification {
  final String id;
  final String companyId;
  final String title;
  final String message;
  final NotificationType type;
  final DateTime createdAt;
  final bool isRead;
  final bool isImportant;
  final Map<String, dynamic> data; // Additional data
  final List<String> relatedIds;   // Related student/internship IDs
  final String? actionUrl;         // Deep link or action
  final String? imageUrl;          // Optional image
  final String? senderId;          // Who sent the notification
  final String? senderName;        // Sender name for display

  CompanyNotification({
    required this.id,
    required this.companyId,
    required this.title,
    required this.message,
    required this.type,
    required this.createdAt,
    this.isRead = false,
    this.isImportant = false,
    this.data = const {},
    this.relatedIds = const [],
    this.actionUrl,
    this.imageUrl,
    this.senderId,
    this.senderName,
  });

  // Factory constructor from Firestore document
  factory CompanyNotification.fromFirestore(
      DocumentSnapshot<Map<String, dynamic>> snapshot,
      SnapshotOptions? options,
      ) {
    final data = snapshot.data()!;
    return CompanyNotification.fromMap(data, snapshot.id);
  }

  // Factory constructor from map
  factory CompanyNotification.fromMap(
      Map<String, dynamic> data,
      String docId,
      ) {
    return CompanyNotification(
      id: docId,
      companyId: data['companyId'] ?? '',
      title: data['title'] ?? '',
      message: data['message'] ?? '',
      type: _parseNotificationType(data['type'] ?? ''),
      createdAt: (data['createdAt'] as Timestamp?)?.toDate() ?? DateTime.now(),
      isRead: data['isRead'] ?? false,
      isImportant: data['isImportant'] ?? false,
      data: Map<String, dynamic>.from(data['data'] ?? {}),
      relatedIds: List<String>.from(data['relatedIds'] ?? []),
      actionUrl: data['actionUrl'],
      imageUrl: data['imageUrl'],
      senderId: data['senderId'],
      senderName: data['senderName'],
    );
  }

  // Factory constructor for creating new notifications
  factory CompanyNotification.create({
    required String companyId,
    required String title,
    required String message,
    required NotificationType type,
    Map<String, dynamic> data = const {},
    List<String> relatedIds = const [],
    String? actionUrl,
    String? imageUrl,
    String? senderId,
    String? senderName,
  }) {
    return CompanyNotification(
      id: '', // Will be generated by Firestore
      companyId: companyId,
      title: title,
      message: message,
      type: type,
      createdAt: DateTime.now(),
      isRead: false,
      isImportant: false,
      data: data,
      relatedIds: relatedIds,
      actionUrl: actionUrl,
      imageUrl: imageUrl,
      senderId: senderId,
      senderName: senderName,
    );
  }

  // Factory constructor for specific notification types
  factory CompanyNotification.newApplication({
    required String companyId,
    required String internshipId,
    required String internshipTitle,
    required String studentId,
    required String studentName,
    required String applicationId,
  }) {
    return CompanyNotification(
      id: '',
      companyId: companyId,
      title: 'New Application Received',
      message: '$studentName has applied for "$internshipTitle"',
      type: NotificationType.newApplication,
      createdAt: DateTime.now(),
      isRead: false,
      isImportant: true,
      data: {
        'internshipId': internshipId,
        'internshipTitle': internshipTitle,
        'studentId': studentId,
        'studentName': studentName,
        'applicationId': applicationId,
      },
      relatedIds: [internshipId, studentId, applicationId],
      actionUrl: '/applications/$applicationId',
      senderId: studentId,
      senderName: studentName,
    );
  }

  factory CompanyNotification.applicationUpdate({
    required String companyId,
    required String applicationId,
    required String studentName,
    required String internshipTitle,
    required String oldStatus,
    required String newStatus,
  }) {
    return CompanyNotification(
      id: '',
      companyId: companyId,
      title: 'Application Status Updated',
      message: 'Application for "$internshipTitle" by $studentName changed from $oldStatus to $newStatus',
      type: NotificationType.applicationUpdate,
      createdAt: DateTime.now(),
      isRead: false,
      isImportant: false,
      data: {
        'applicationId': applicationId,
        'studentName': studentName,
        'internshipTitle': internshipTitle,
        'oldStatus': oldStatus,
        'newStatus': newStatus,
      },
      relatedIds: [applicationId],
      actionUrl: '/applications/$applicationId',
    );
  }

  factory CompanyNotification.studentMessage({
    required String companyId,
    required String studentId,
    required String studentName,
    required String messagePreview,
    required String chatId,
  }) {
    return CompanyNotification(
      id: '',
      companyId: companyId,
      title: 'New Message from $studentName',
      message: messagePreview,
      type: NotificationType.studentMessage,
      createdAt: DateTime.now(),
      isRead: false,
      isImportant: false,
      data: {
        'studentId': studentId,
        'studentName': studentName,
        'chatId': chatId,
        'messagePreview': messagePreview,
      },
      relatedIds: [studentId, chatId],
      actionUrl: '/chat/$chatId',
      senderId: studentId,
      senderName: studentName,
    );
  }

  factory CompanyNotification.studentDocument({
    required String companyId,
    required String studentId,
    required String studentName,
    required String documentType,
    required String documentUrl,
  }) {
    return CompanyNotification(
      id: '',
      companyId: companyId,
      title: 'New Document Uploaded',
      message: '$studentName uploaded a new $documentType',
      type: NotificationType.studentDocument,
      createdAt: DateTime.now(),
      isRead: false,
      isImportant: false,
      data: {
        'studentId': studentId,
        'studentName': studentName,
        'documentType': documentType,
        'documentUrl': documentUrl,
      },
      relatedIds: [studentId],
      actionUrl: documentUrl,
      senderId: studentId,
      senderName: studentName,
    );
  }

  factory CompanyNotification.systemAlert({
    required String companyId,
    required String alertType,
    required String alertMessage,
    String? actionRequired,
  }) {
    return CompanyNotification(
      id: '',
      companyId: companyId,
      title: 'System Alert: $alertType',
      message: alertMessage,
      type: NotificationType.systemAlert,
      createdAt: DateTime.now(),
      isRead: false,
      isImportant: true,
      data: {
        'alertType': alertType,
        'alertMessage': alertMessage,
        'actionRequired': actionRequired,
      },
      actionUrl: actionRequired != null ? '/system/alerts' : null,
    );
  }

  factory CompanyNotification.payment({
    required String companyId,
    required String paymentId,
    required String amount,
    required String status,
    required String description,
  }) {
    return CompanyNotification(
      id: '',
      companyId: companyId,
      title: 'Payment $status',
      message: 'Payment of $amount: $description',
      type: NotificationType.payment,
      createdAt: DateTime.now(),
      isRead: false,
      isImportant: true,
      data: {
        'paymentId': paymentId,
        'amount': amount,
        'status': status,
        'description': description,
      },
      relatedIds: [paymentId],
      actionUrl: '/payments/$paymentId',
    );
  }

  factory CompanyNotification.reminder({
    required String companyId,
    required String reminderType,
    required String message,
    required DateTime dueDate,
    required List<String> relatedIds,
  }) {
    return CompanyNotification(
      id: '',
      companyId: companyId,
      title: 'Reminder: $reminderType',
      message: message,
      type: NotificationType.reminder,
      createdAt: DateTime.now(),
      isRead: false,
      isImportant: false,
      data: {
        'reminderType': reminderType,
        'dueDate': dueDate.toIso8601String(),
        'daysLeft': dueDate.difference(DateTime.now()).inDays,
      },
      relatedIds: relatedIds,
      actionUrl: '/reminders',
    );
  }

  factory CompanyNotification.internshipClosed({
    required String companyId,
    required String internshipId,
    required String internshipTitle,
    required int totalApplications,
  }) {
    return CompanyNotification(
      id: '',
      companyId: companyId,
      title: 'Internship Closed',
      message: '"$internshipTitle" has been closed with $totalApplications applications',
      type: NotificationType.internshipClosed,
      createdAt: DateTime.now(),
      isRead: false,
      isImportant: false,
      data: {
        'internshipId': internshipId,
        'internshipTitle': internshipTitle,
        'totalApplications': totalApplications,
        'closedAt': DateTime.now().toIso8601String(),
      },
      relatedIds: [internshipId],
      actionUrl: '/internships/$internshipId',
    );
  }

  factory CompanyNotification.lowSlots({
    required String companyId,
    required int remainingSlots,
    required int threshold,
  }) {
    return CompanyNotification(
      id: '',
      companyId: companyId,
      title: 'Low Slot Alert',
      message: 'You have $remainingSlots slots remaining (below $threshold threshold)',
      type: NotificationType.lowSlots,
      createdAt: DateTime.now(),
      isRead: false,
      isImportant: true,
      data: {
        'remainingSlots': remainingSlots,
        'threshold': threshold,
        'alertLevel': remainingSlots < 10 ? 'critical' : 'warning',
      },
      actionUrl: '/billing/slots',
    );
  }

  // Convert to map for Firestore
  Map<String, dynamic> toMap() {
    return {
      'companyId': companyId,
      'title': title,
      'message': message,
      'type': _notificationTypeToString(type),
      'createdAt': Timestamp.fromDate(createdAt),
      'isRead': isRead,
      'isImportant': isImportant,
      'data': data,
      'relatedIds': relatedIds,
      if (actionUrl != null) 'actionUrl': actionUrl,
      if (imageUrl != null) 'imageUrl': imageUrl,
      if (senderId != null) 'senderId': senderId,
      if (senderName != null) 'senderName': senderName,
    };
  }

  // Convert to Firestore format
  Map<String, dynamic> toFirestore() {
    return toMap();
  }

  // Copy with method for updates
  CompanyNotification copyWith({
    String? id,
    String? companyId,
    String? title,
    String? message,
    NotificationType? type,
    DateTime? createdAt,
    bool? isRead,
    bool? isImportant,
    Map<String, dynamic>? data,
    List<String>? relatedIds,
    String? actionUrl,
    String? imageUrl,
    String? senderId,
    String? senderName,
  }) {
    return CompanyNotification(
      id: id ?? this.id,
      companyId: companyId ?? this.companyId,
      title: title ?? this.title,
      message: message ?? this.message,
      type: type ?? this.type,
      createdAt: createdAt ?? this.createdAt,
      isRead: isRead ?? this.isRead,
      isImportant: isImportant ?? this.isImportant,
      data: data ?? this.data,
      relatedIds: relatedIds ?? this.relatedIds,
      actionUrl: actionUrl ?? this.actionUrl,
      imageUrl: imageUrl ?? this.imageUrl,
      senderId: senderId ?? this.senderId,
      senderName: senderName ?? this.senderName,
    );
  }

  // Mark as read
  CompanyNotification markAsRead() {
    return copyWith(isRead: true);
  }

  // Mark as unread
  CompanyNotification markAsUnread() {
    return copyWith(isRead: false);
  }

  // Toggle important
  CompanyNotification toggleImportant() {
    return copyWith(isImportant: !isImportant);
  }

  // Helper methods
  bool get requiresAction {
    return type == NotificationType.newApplication ||
        type == NotificationType.studentMessage ||
        type == NotificationType.systemAlert ||
        type == NotificationType.lowSlots;
  }

  bool get isUrgent {
    return type == NotificationType.systemAlert ||
        (type == NotificationType.newApplication && data['priority'] == 'high') ||
        type == NotificationType.lowSlots;
  }

  String get category {
    switch (type) {
      case NotificationType.newApplication:
      case NotificationType.applicationUpdate:
        return 'Applications';
      case NotificationType.studentMessage:
      case NotificationType.studentDocument:
        return 'Students';
      case NotificationType.systemAlert:
      case NotificationType.payment:
        return 'System';
      case NotificationType.reminder:
      case NotificationType.report:
        return 'Reminders';
      case NotificationType.announcement:
        return 'Announcements';
      case NotificationType.internshipClosed:
      case NotificationType.internshipCreated:
        return 'Internships';
      case NotificationType.lowSlots:
        return 'Billing';
      case NotificationType.verification:
        return 'Verification';
    }
  }

  String get iconName {
    switch (type) {
      case NotificationType.newApplication:
        return 'application';
      case NotificationType.applicationUpdate:
        return 'update';
      case NotificationType.studentMessage:
        return 'message';
      case NotificationType.studentDocument:
        return 'document';
      case NotificationType.systemAlert:
        return 'alert';
      case NotificationType.payment:
        return 'payment';
      case NotificationType.reminder:
        return 'reminder';
      case NotificationType.report:
        return 'report';
      case NotificationType.announcement:
        return 'announcement';
      case NotificationType.internshipClosed:
        return 'close';
      case NotificationType.internshipCreated:
        return 'add';
      case NotificationType.lowSlots:
        return 'warning';
      case NotificationType.verification:
        return 'verified';
    }
  }

  Color get color {
    switch (type) {
      case NotificationType.newApplication:
        return const Color(0xFF4CAF50); // Green
      case NotificationType.applicationUpdate:
        return const Color(0xFF2196F3); // Blue
      case NotificationType.studentMessage:
        return const Color(0xFF9C27B0); // Purple
      case NotificationType.studentDocument:
        return const Color(0xFFFF9800); // Orange
      case NotificationType.systemAlert:
        return const Color(0xFFF44336); // Red
      case NotificationType.payment:
        return const Color(0xFF009688); // Teal
      case NotificationType.reminder:
        return const Color(0xFFFFC107); // Amber
      case NotificationType.report:
        return const Color(0xFF795548); // Brown
      case NotificationType.announcement:
        return const Color(0xFF3F51B5); // Indigo
      case NotificationType.internshipClosed:
        return const Color(0xFF607D8B); // Blue Grey
      case NotificationType.internshipCreated:
        return const Color(0xFF00BCD4); // Cyan
      case NotificationType.lowSlots:
        return const Color(0xFFE91E63); // Pink
      case NotificationType.verification:
        return const Color(0xFF8BC34A); // Light Green
    }
  }

  // Static helper methods
  static NotificationType _parseNotificationType(String typeString) {
    switch (typeString.toLowerCase()) {
      case 'new_application':
        return NotificationType.newApplication;
      case 'application_update':
        return NotificationType.applicationUpdate;
      case 'student_message':
        return NotificationType.studentMessage;
      case 'student_document':
        return NotificationType.studentDocument;
      case 'system_alert':
        return NotificationType.systemAlert;
      case 'payment':
        return NotificationType.payment;
      case 'reminder':
        return NotificationType.reminder;
      case 'report':
        return NotificationType.report;
      case 'announcement':
        return NotificationType.announcement;
      case 'internship_closed':
        return NotificationType.internshipClosed;
      case 'internship_created':
        return NotificationType.internshipCreated;
      case 'low_slots':
        return NotificationType.lowSlots;
      case 'verification':
        return NotificationType.verification;
      default:
        return NotificationType.systemAlert;
    }
  }

  static String _notificationTypeToString(NotificationType type) {
    switch (type) {
      case NotificationType.newApplication:
        return 'new_application';
      case NotificationType.applicationUpdate:
        return 'application_update';
      case NotificationType.studentMessage:
        return 'student_message';
      case NotificationType.studentDocument:
        return 'student_document';
      case NotificationType.systemAlert:
        return 'system_alert';
      case NotificationType.payment:
        return 'payment';
      case NotificationType.reminder:
        return 'reminder';
      case NotificationType.report:
        return 'report';
      case NotificationType.announcement:
        return 'announcement';
      case NotificationType.internshipClosed:
        return 'internship_closed';
      case NotificationType.internshipCreated:
        return 'internship_created';
      case NotificationType.lowSlots:
        return 'low_slots';
      case NotificationType.verification:
        return 'verification';
    }
  }

  // Predefined notification templates
  static Map<NotificationType, Map<String, dynamic>> templates = {
    NotificationType.newApplication: {
      'title': 'New Application Received',
      'icon': Icons.person_add,
      'color': Colors.green,
    },
    NotificationType.applicationUpdate: {
      'title': 'Application Updated',
      'icon': Icons.update,
      'color': Colors.blue,
    },
    NotificationType.studentMessage: {
      'title': 'New Message',
      'icon': Icons.message,
      'color': Colors.purple,
    },
    NotificationType.systemAlert: {
      'title': 'System Alert',
      'icon': Icons.warning,
      'color': Colors.red,
    },
    NotificationType.payment: {
      'title': 'Payment Notification',
      'icon': Icons.payment,
      'color': Colors.teal,
    },
  };

  @override
  String toString() {
    return 'CompanyNotification{id: $id, title: $title, type: $type, isRead: $isRead, createdAt: $createdAt}';
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
          other is CompanyNotification &&
              runtimeType == other.runtimeType &&
              id == other.id &&
              companyId == other.companyId;

  @override
  int get hashCode => id.hashCode ^ companyId.hashCode;
}


